real_robot:
  controller_manager:
    ros__parameters:
      update_rate: 100 # update_rate specifies how often (in Hz) the controllers should be updated.

      # The JointTrajectoryController allows you to send joint trajectory commands to a group
      # of joints on a robot. These commands specify the desired positions for each joint.


      # Responsible for publishing the current state of the robot's joints to the /joint_states
      # ROS 2 topic
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  real_arm_controller:
    ros__parameters:
      type: joint_trajectory_controller/JointTrajectoryController

      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_gripper_body


      # The controller will expect position commands as input for each of these joints.
      command_interfaces:
        - position

      # Tells the controller that it should expect to receive position data as the state
      # feedback from the hardware interface,
      state_interfaces:
        - position

  real_state_controller:
    ros__parameters:
      type: joint_state_broadcaster/JointStateBroadcaster

  real_gripper_controller:
    ros__parameters:
      type: joint_trajectory_controller/JointTrajectoryController

      joints:
        - joint_gripper_left_part

      command_interfaces:
        - position

      state_interfaces:
        - position

